export const spookySentences = [
  "The undead shuffled closer as the moon vanished behind thick, swirling clouds; every breath felt colder in the abandoned streets, and the silence was shattered only by distant, chilling groans echoing through the night.",
  "Shadows crawled across the crumbling walls while distant moans grew louder, carrying the promise of danger; there was no time to hide, no place to run, and every step forward felt heavier than the last.",
  "The safe house was a cruel lie, its broken windows and scattered blood telling a story she desperately did not want to hear; the weight of fear pressed down on her, crushing every ounce of hope.",
  "He clutched the makeshift weapon tighter, heart racing, as the dead reached their skeletal hands through the boarded-up door; survival was slipping away like sand through his fingers, leaving only despair in its wake.",
  "Footsteps pounded relentlessly behind her, but she dared not look back; one wrong glance, one moment of hesitation, and the relentless horde would close the distance, dragging her into the abyss of the undead.",
  "The empty alley smelled of decay and ancient fear; something unseen moved just beyond the edge of the streetlight’s flicker, waiting patiently for its next victim to stumble into its grasp.",
  "Lights flickered sporadically on the broken streetlamp while mournful moans echoed from the depths of the shadows; tonight, there was no escape, only the cold certainty of death stalking every corner.",
  "She ran faster, heart pounding as rotten hands clawed at her jacket; the city around her was a graveyard, painted with silence and screams that echoed through the empty, lifeless streets.",
  "The last radio broadcast warned of the infected hordes closing in from every direction; hope was as thin as the fading daylight, slipping through her fingers like a ghost she could never hold.",
  "In the quiet moments before dawn, only rustling leaves and distant growls reminded her that she was not alone in the darkness; every sound was a warning, every shadow a threat lurking just beyond sight.",
  "The hallway stretched longer with every step she took, the peeling wallpaper whispering secrets she didn't want to hear; somewhere ahead, a door creaked open slowly, though no footsteps had ever reached it.",
  "Rain lashed against the broken windows, and each thunderclap seemed to come closer than the last; beneath the floorboards, something moved with intention, matching her breath, matching her fear.",
  "He lit a single match to chase the darkness from the basement, but shadows ignored the flame; they pulsed along the walls, thick with hunger, waiting for the moment the light died again.",
  "She stepped into the room and immediately knew she wasn’t alone; the air was too still, too silent, except for the faint sound of breathing that did not belong to her.",
  "The forest swallowed her whole, branches closing in like fingers, muffling every cry for help; somewhere in the distance, bells rang—a melody twisted and broken, calling her deeper into the trees.",
  "The mirrors in the house did not show her reflection anymore; instead, they displayed flickers of someone else’s memories, bloody fingerprints, and faces that vanished whenever she blinked.",
  "Cold fingers brushed her shoulder, though she stood alone in the room; the lights flickered once, then died completely, leaving only the sound of shuffling steps behind her.",
  "He screamed, but the fog swallowed the sound; it was thick, alive, crawling with whispers that circled his thoughts and urged him to stop running, to accept the darkness reaching for him.",
  "The walls were bleeding, though no one had been inside for decades; something laughed from the upper floor, not a voice, but a presence that made the bones beneath her skin vibrate.",
  "She woke up in her own bed, but the sky outside was black at noon, and her house no longer had doors—only windows that looked into places she had never seen before.",
  "He held his breath as the groan echoed through the stairwell—closer this time—and prayed the barricade would hold just one more hour, maybe even less.",
  "The radio crackled with static, then a voice: 'Sector Seven is lost—repeat, lost!' before cutting out, leaving them surrounded and with nowhere to go but through the mist.",
  "They had five bullets left, no food, and a map stained with someone else's blood; the plan was madness, but staying meant certain death.",
  "Footsteps—no, not footsteps, something wetter—slapped across the concrete behind them, and when she turned, it was already too late to scream.",
  "A child’s laughter echoed from the fog-drenched alleyway, far too cheerful for this ruined city; he gripped his axe tighter and backed away slowly.",
  "Even in daylight, the sky remained gray and lifeless, as if the sun had long abandoned this place to the rotting dead and the mad survivors.",
  "They ran until their lungs burned, chased not by zombies but by the dread of stopping; it wasn’t just survival anymore—it was punishment.",
  "The town square, once full of life, was now a graveyard of overturned cars, flickering signs, and the twitching corpses that hadn’t realized they were dead.",
  "Blood smeared handprints lined the hallway, each one fresh, each one lower, like something was crawling—no, dragging—itself toward them slowly.",
  "She whispered a prayer to no one in particular, the shotgun heavy in her hands and the thudding footsteps impossibly close behind.",
  "When the power finally failed, darkness didn’t come—it surged, alive with groans, rattling vents, and the scraping of dead fingers on metal.",
  "They thought the sewers were safe until the echoes changed; wet, shambling echoes that didn’t come from their own feet anymore.",
  "A siren wailed in the distance, then silence—total, perfect silence—before the unmistakable sound of teeth on bone broke the night apart.",
  "He scrawled 'Don't trust the living either' in blood on the wall and disappeared into the fog, leaving the door swinging open.",
  "The hospital lights flickered erratically, casting just enough light to see movement—but never long enough to know what it was.",
  "Every path was blocked, every door jammed, every street crawling with death; still, she ran, driven by a memory she couldn’t forget.",
  "Their flashlights dimmed one by one as the group stumbled through the subway tunnels, chased by shadows that didn’t need light to see.",
  "Through the cracked glass of her mask, she watched the city burn—quietly, hopelessly—as the infected clawed at the gates below.",
];
